# Generated by Django 4.1.5 on 2023-01-16 23:06

import autoslug.fields
import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import marketplace.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from=models.CharField(max_length=100), slugify=marketplace.models.Category.custom_slugify)),
            ],
        ),
        migrations.CreateModel(
            name='NftCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('logo_image', models.ImageField(upload_to='')),
                ('banner_image', models.ImageField(upload_to='')),
                ('featured_image', models.ImageField(upload_to='')),
                ('name', models.CharField(max_length=100)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from=models.CharField(max_length=100), slugify=marketplace.models.NftCollection.custom_slugify)),
                ('description', models.TextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_category', to='marketplace.category')),
                ('user_collection', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_collections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CreateNftModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name', slugify=marketplace.models.CreateNftModel.custom_slugify, unique_with=['created__month'])),
                ('description', models.TextField()),
                ('item_price', models.FloatField()),
                ('size', models.CharField(blank=True, max_length=100)),
                ('upload_nft', cloudinary.models.CloudinaryField(max_length=255, verbose_name='file')),
                ('properties', models.CharField(blank=True, max_length=255)),
                ('royalties', models.CharField(blank=True, max_length=100)),
                ('nft_type', models.CharField(choices=[('art', 'art'), ('video', 'video'), ('music', 'music'), ('trading-cards/collectible', 'trading-cards/collectible'), ('text', 'text'), ('memes', 'memes'), ('domain-names', 'domain-names'), ('virtual-style', 'virtual-style'), ('incidental-internet-based-things', 'incidental-internet-based-things'), ('pdf', 'pdf')], default='art', max_length=100)),
                ('bid', models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default='NO', max_length=5)),
                ('status', models.CharField(choices=[('BUY', 'BUY'), ('SOLD', 'SOLD')], default='BUY', max_length=10)),
                ('list_for_sale', models.BooleanField(default=True)),
                ('minted', models.BooleanField(default=False)),
                ('gas_fee', models.FloatField(default=0.018)),
                ('collection', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='nft_collections', to='marketplace.nftcollection')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='creator_nft', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BidNft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid_amount', models.FloatField()),
                ('end_bid', models.BooleanField(default=False)),
                ('bid_item', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='marketplace.createnftmodel')),
                ('bid_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
