# Generated by Django 4.1.5 on 2023-03-06 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nftcollection',
            name='logo_image',
            field=models.ImageField(blank=True, default='ks.png', null=True, upload_to=''),
        ),
    ]
