# Generated by Django 4.1.5 on 2023-01-16 23:42

import autoslug.fields
import cloudinary.models
from django.db import migrations
import marketplace.models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='name', slugify=marketplace.models.Category.custom_slugify),
        ),
        migrations.AlterField(
            model_name='nftcollection',
            name='banner_image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='raw'),
        ),
        migrations.AlterField(
            model_name='nftcollection',
            name='featured_image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='nftcollection',
            name='logo_image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='nftcollection',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='name', slugify=marketplace.models.NftCollection.custom_slugify),
        ),
    ]
