# Generated by Django 4.1.5 on 2023-03-06 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_alter_nftcollection_logo_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nftcollection',
            name='banner_image',
            field=models.ImageField(blank=True, default='', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='nftcollection',
            name='featured_image',
            field=models.ImageField(blank=True, default='', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='nftcollection',
            name='logo_image',
            field=models.ImageField(blank=True, default='', null=True, upload_to=''),
        ),
    ]
