# Generated by Django 4.1.5 on 2023-01-21 13:03

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_alter_category_slug_alter_nftcollection_banner_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createnftmodel',
            name='upload_nft',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='raw'),
        ),
    ]
