# Generated by Django 4.1.5 on 2023-01-23 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_alter_createnftmodel_upload_nft'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createnftmodel',
            name='nft_type',
            field=models.CharField(choices=[('art', 'Art'), ('video', 'Video'), ('music', 'Music'), ('trading-cards/collectible', 'Trading Card Or Collectible'), ('text', 'Text'), ('memes', 'Memes'), ('domain-name', 'Domain Name'), ('virtual-style', 'Virtual Style'), ('pdf', 'Pdf')], default='art', max_length=100),
        ),
    ]
