# Generated by Django 4.1.5 on 2023-01-25 03:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0005_alter_createnftmodel_upload_nft'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createnftmodel',
            name='collection',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.DO_NOTHING, related_name='nft_collections', to='marketplace.nftcollection'),
        ),
    ]
