# Generated by Django 4.1.5 on 2023-01-25 04:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0007_alter_createnftmodel_collection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createnftmodel',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nft_collections', to='marketplace.nftcollection'),
        ),
    ]
