# Generated by Django 4.1.5 on 2023-01-25 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0009_createnftmodel_purchased_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='nftcollection',
            name='explicit_content',
            field=models.BooleanField(default=False),
        ),
    ]
