# Generated by Django 4.1.5 on 2023-01-25 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0010_nftcollection_explicit_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='nftcollection',
            name='blockchain',
            field=models.CharField(blank=True, default='Ethereum', max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='nftcollection',
            name='creator_earning',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nftcollection',
            name='payout_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
