# Generated by Django 4.1.5 on 2023-01-26 08:23

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0011_nftcollection_blockchain_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nftcollection',
            name='customize_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nftcollection',
            name='banner_image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='nftcollection',
            name='blockchain',
            field=models.CharField(choices=[('ethereum', 'Ethereum'), ('polygon', 'Polygon'), ('solana', 'Solana')], default='ethereum', max_length=40),
        ),
        migrations.AlterField(
            model_name='nftcollection',
            name='creator_earning',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='nftcollection',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nftcollection',
            name='logo_image',
            field=cloudinary.models.CloudinaryField(default='', max_length=255, verbose_name='image'),
        ),
    ]
