# Generated by Django 4.1.5 on 2023-01-26 08:57

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0012_nftcollection_customize_url_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nftcollection',
            old_name='customize_url',
            new_name='custom_url',
        ),
        migrations.AlterField(
            model_name='nftcollection',
            name='banner_image',
            field=cloudinary.models.CloudinaryField(default='https://res.cloudinary.com/dbbfeegje/image/upload/v1674723307/collection-cover_hcgj4r.png', max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='nftcollection',
            name='featured_image',
            field=cloudinary.models.CloudinaryField(default='https://res.cloudinary.com/dbbfeegje/image/upload/v1674723307/collection-featured_lqyqxe.jpg', max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='nftcollection',
            name='logo_image',
            field=cloudinary.models.CloudinaryField(default='https://res.cloudinary.com/dbbfeegje/image/upload/v1674723310/collection-logo_yig2la.jpg', max_length=255, verbose_name='image'),
        ),
    ]
