# Generated by Django 4.1.5 on 2023-01-29 22:28

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0014_rename_explicit_content_nftcollection_sensitive_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createnftmodel',
            name='upload_nft',
            field=cloudinary.models.CloudinaryField(blank=True, default='https://res.cloudinary.com/dbbfeegje/image/upload/v1674443265/coll-item-2_vqfk6q.jpg', max_length=255),
        ),
    ]
