# Generated by Django 4.1.5 on 2023-02-01 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0016_createnftmodel_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidnft',
            name='bid_item',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='marketplace.createnftmodel'),
        ),
    ]
