# Generated by Django 4.1.5 on 2023-02-01 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0017_alter_bidnft_bid_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidnft',
            name='bid_item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='marketplace.createnftmodel'),
        ),
    ]
