# Generated by Django 4.1.5 on 2023-02-06 16:06

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0018_alter_bidnft_bid_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='createnftmodel',
            name='mint_proof',
            field=cloudinary.models.CloudinaryField(blank=True, default='', max_length=255),
        ),
    ]
