# Generated by Django 4.1.5 on 2023-02-06 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0019_createnftmodel_mint_proof'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createnftmodel',
            name='mint_proof',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='createnftmodel',
            name='upload_nft',
            field=models.FileField(blank=True, default='https://res.cloudinary.com/dbbfeegje/image/upload/v1674443265/coll-item-2_vqfk6q.jpg', null=True, upload_to=''),
        ),
    ]
