# Generated by Django 4.1.5 on 2023-02-06 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0020_alter_createnftmodel_mint_proof_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createnftmodel',
            name='gas_fee',
            field=models.FloatField(default=0.18),
        ),
    ]
