# Generated by Django 4.1.5 on 2023-01-21 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_moredetails_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moredetails',
            name='gender',
            field=models.CharField(choices=[], default='', max_length=100),
        ),
    ]
