# Generated by Django 4.1.5 on 2023-01-30 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_moredetails_created_moredetails_modified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userwallet',
            name='wallet_address',
            field=models.TextField(max_length=255),
        ),
    ]
