# Generated by Django 4.1.5 on 2023-01-30 21:19

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_userwallet_wallet_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertransactions',
            name='upload_proof',
            field=cloudinary.models.CloudinaryField(default='https://res.cloudinary.com/dbbfeegje/image/upload/v1673299668/cld-sample-2.jpg', max_length=255, verbose_name='image'),
        ),
    ]
