# Generated by Django 4.1.5 on 2023-01-30 21:22

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_usertransactions_upload_proof'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertransactions',
            name='upload_proof',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
