# Generated by Django 4.1.5 on 2023-01-30 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lighthouse', '0003_alter_paymentmethod_coin_qr_code'),
        ('accounts', '0014_usertransactions_w_wallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertransactions',
            name='wallet_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='payment_type', to='lighthouse.paymentmethod'),
        ),
    ]
