# Generated by Django 4.1.5 on 2023-02-08 02:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lighthouse', '0004_alter_paymentmethod_coin_qr_code'),
        ('accounts', '0018_alter_user_cover_photo_alter_user_profile_pic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertransactions',
            name='wallet_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_type', to='lighthouse.paymentmethod'),
        ),
    ]
