# Generated by Django 4.1.5 on 2023-02-10 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_alter_usertransactions_wallet_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertransactions',
            name='w_gas_fee',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
