# Generated by Django 4.1.5 on 2023-02-06 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lighthouse', '0003_alter_paymentmethod_coin_qr_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='coin_qr_code',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
