# Generated by Django 4.1.5 on 2023-02-08 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lighthouse', '0004_alter_paymentmethod_coin_qr_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='coin_qr_code',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
